runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /assets
  static_dir: assets

- url: /images
  static_dir: images

- url: /api/beiras_rnn
  script: main.app

- url: /index-gal.html
  static_files: index-gal.html
  upload: index-gal.html

- url: /.*
  static_files: index.html
  upload: index.html





libraries:
- name: numpy
  version: "1.6.1"
