runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /assets
  static_dir: assets

- url: /images
  static_dir: images


- url: /api/beiras_rnn
  script: main.app

- url: /.*
  static_files: index.html
  upload: index.html





libraries:
- name: numpy
  version: "1.6.1"
