runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /jquery-3.2.1.min.js
  static_files: jquery-3.2.1.min.js
  upload: jquery-3.2.1.min.js


- url: /api/beiras_rnn
  script: main.app
  
- url: /.*
  static_files: index.html
  upload: index.html





libraries:
- name: numpy
  version: "1.6.1"
